name: Sync README and NOTICE

on:
  push:
    branches:
      - main
    paths:
      - README.md

jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Copy README.md to NOTICE
        run: cp README.md NOTICE
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add NOTICE
          git commit -m 'Sync README.md with NOTICE'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
